### PR TITLE
Fixed gap in upper left corner of 160x100 EuroBoards.

### PR DESCRIPTION
**Pull request by DavidGriffith**
I can't fathom why a gap in the Edge.Cuts layer would be desirable.

### CODE REVIEW

**Comment by poeschlr** [comment]
All the coordinates of these footprints look a bit strange to me. Maybe there has been a conversion issue between the old format and the current format?

Would you care to check all corners and make sure they are on sane coordinates? (As an example it should be 160 instead of 159.99968)

The same is true for the hole positions.

**Comment by DavidGriffith** [comment]
I was scratching my head over the weird decimals too.  Then I really got it when I tried to put a connector on it -- the holes didn't line up.  I'll fix those up in a bit.

**Comment by bobc** [comment]
This library is marked as deprecated, so I guess at some random point in the future it will be deleted.

What we need is a script that converts footprints to project templates.

**Comment by DavidGriffith** [comment]
Are there any guidelines for at least manually converting these into project templates?

**Comment by evanshultz** [comment]
All that I know about is at http://docs.kicad-pcb.org/stable/en/kicad.html#_using_templates.

**Comment by Shackmeister** [comment]
Perhaps it could be considered to draw the outline  in a kicad_pcb file and save/share that. To use it the "append board" function in PCBnew stabdalone could be used

**Comment by DavidGriffith** [comment]
I think I can take on that task.  In the meantime, could I get someone to approve this pull request?

**Comment by DavidGriffith** [comment]
I think I have template creation figured out.  I'll be converting these footprints to templates over the coming week.  So far, I have the two 160x100 boards done.

**Comment by poeschlr** [comment]
The changes you made to these footprints look good. If you want to share your templates we will be happy to welcome them here. templates are currently added to the main [kicad-library repo](https://github.com/KiCad/kicad-library/tree/master/template)

**Comment by DavidGriffith** [comment]
The templates are already in a pull-request in kicad-library (see above).

**Pull request merged**
